server:
  port: 8203
spring:
  application:
    name: Service-User
  profiles:
    active: dev # 环境设置
  # 连接mysql数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.128:3306/medical_user?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Luo@123456
  # 设置返回json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    # 注册中心
    nacos:
      server-addr: 192.168.43.128:8848
  # Redis
  redis:
    host: 192.168.43.128
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
# mapper XML文件的路径
mybatis-plus:
  mapper-locations: classpath:com/medical/mapper/*.xml
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_uri: http://localhost:8160/api/ucenter/wx/callback
site:
  baseUrl: http://localhost:3000